<?php

namespace AppBundle\Repository;

/**
 * ChatUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatUserRepository extends \Doctrine\ORM\EntityRepository
{
}
