parameters:
    app.chat.handler.class: AppBundle\Handler\ChatHandler

services:
    app.chat.handler:
        class: %app.chat.handler.class%
        arguments: [@service_container, @doctrine.orm.entity_manager]